#####################################################
#   Baixar arquivo com CadPro ativos no PR  
#   Tema do Chrome CLARO - Com Screenshot           #
#####################################################

#Bibliotecas
import pyautogui
import time

pyautogui.hotkey('winleft')
pyautogui.write('chome', interval=0.50)
pyautogui.press('enter')
pyautogui.hotkey('ctrl', 't')
time.sleep(1.0)
pyautogui.write('http://processos.fazenda.pr.gov.br/arquivos/pubcadpro', interval=0.10)
pyautogui.press('enter')            
time.sleep(5.0)
imgChrome = pyautogui.locateCenterOnScreen('_base\_mov5.png', confidence=0.7)
time.sleep(2)
pyautogui.click(imgChrome)
time.sleep(2)
pyautogui.press('up')
time.sleep(2)
pyautogui.press('up')
time.sleep(2)
pyautogui.press('enter')
time.sleep(3)
imgExibirDownloads = pyautogui.locateCenterOnScreen('_base\_exibirDownloadsW.png', confidence=0.7)
time.sleep(2)
pyautogui.click(imgExibirDownloads)
time.sleep(2)
imgMostrarNaPasta = pyautogui.locateCenterOnScreen('_base\_mostrarPastaW.png', confidence=0.7)
time.sleep(2)
pyautogui.click(imgMostrarNaPasta)
time.sleep(2)
pyautogui.hotkey('ctrl', 'x')
time.sleep(2)
pyautogui.hotkey('winleft', 'r')
time.sleep(2)
pyautogui.write('C:\cadpro', interval=0.10)
time.sleep(2)
pyautogui.press('enter')
time.sleep(2)
pyautogui.hotkey('ctrl', 'v')
time.sleep(2)
imgClicaExtrair = pyautogui.locateCenterOnScreen('_base\_iconeW.png', confidence=0.7)
time.sleep(2)
pyautogui.click(imgClicaExtrair)
time.sleep(2)
pyautogui.click(button='right')
time.sleep(2)
imgClickDireito = pyautogui.locateCenterOnScreen('_base\_extrairW.png', confidence=0.9)
time.sleep(2)
pyautogui.click(imgClickDireito)
time.sleep(5)
imgConfirmaExtrair = pyautogui.locateCenterOnScreen('_base\_ConfirmaExtrair.png', confidence=0.9)
time.sleep(2)
pyautogui.click(imgConfirmaExtrair)
time.sleep(5)
pyautogui.press('space')
time.sleep(3)
pyautogui.hotkey('shift', 'del')
time.sleep(3)
pyautogui.press('enter')
time.sleep(3)

#pyinstaller --onefile --hiddenimport pyautogui .\bot_cadpro.py

exit()